### PR TITLE
Fix UUID for Darwin hosts

### PR DESCRIPTION
**Pull request by dcarbone**
- Addresses #100 based on fix suggested by @rpendleton
- Adds multi-platform matrix run strategy to actions
- Adds .gitignore file
- Address #78

### CODE REVIEW

**Comment by dcarbone** [comment]
Should be noted that I do not have a Darwin machine handy to test this on, thus I'm relying on gha runners :D

**Comment by rs** [comment]
Thanks for the PR. Could you please check the failing tests?

**Comment by rs** [comment]
Thanks. It is still failing due to some wrong build tags apparently.

**Comment by rs** [comment]
Damn there is now a lint issue on windows. Do you mind applying the recommendation to make it pass? Thanks!

**Comment by dcarbone** [comment]
@rs Sorry again for the delay!  Windows lint issues addressed :)

**Comment by dcarbone** [comment]
@rs Sorry to bug you, but I believe the last of the issues have been adressed :)

**Comment by rs** [comment]
There is no change of API or anything non-backward compatible, so it should remain a minor. Do I miss something?

**Comment by dcarbone** [comment]
A key value source is different for Darwin now, no?  I don't have a Darwin host to compare & contrast, unfortunately...

**Comment by rs** [comment]
How is that affecting compatibility?

**Comment by dcarbone** [comment]
If they generate a key on the same host using a lib with the previous mechanism, it will not match a value created with this change.

**Comment by rs** [comment]
What do you mean by "match"? The lib is meant to generate unique ids, two values generated from the lib should never match regardless of :)

**Comment by dcarbone** [comment]
Ah, but the individual components are comparable, too, no?

**Comment by rs** [comment]
There is no guarantee the machine id would stay stable across versions.

**Comment by dcarbone** [comment]
Fair enough 😄

**Pull request merged**
