### PR TITLE
Very minor issue: Making the error variable private/local, but its global so worth while

### PR DESCRIPTION
**Pull request by wade-welles**

### CODE REVIEW

**Comment by rs** [comment]
Why?

**Comment by wade-welles** [comment]
So its not included or accessible outside the package. Variables that are only within the scope of the package should be local/private. Its minor but it should affect the resource footprint, since it would be in memory less often. 

Unless you see a context in which that variable woudl be useful outside the package. It is pretty minor and I would take no offense to rejecting it, just saw it and thought itd push it.

**Comment by rs** [comment]
It's provided on purpose so you can compare the error you get to this specific type of error.

**Comment by wade-welles** [comment]
Okay, thanks for explanation. Just wasnt sure because the randErr wasnt exported. Just figured it was a minor consistency mistake.

**Comment by rs** [comment]
the randErr is never returned, it would panic instead.

**Comment by smyrman** [comment]
It is possible to make the error _constant_ rather than a global variable (to prevent it being edited):

```go
type constErr string

func (err constErr) Error() string {
   return string(err)
}

const ErrInvalid = errors.New("xid: invalid ID")
```

However the `var Err...` pattern for declaring "error predicates", although possible to tamper with, is pretty common, also so inside the standard library.

**Comment by smyrman** [comment]
The error has been made `const` on the master branch; should be fine to close this PR now.

**Pull request closed without merging**
